services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    image: apache/airflow:2.10.2-python3.9
    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: ${EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.10.2-python3.9
    depends_on:
      - airflow-webserver
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: ${EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    command: scheduler
    restart: always
